### PR TITLE
Updates & Refactoring.

### PR DESCRIPTION
**Pull request by ousid**
Fixing Typo on `getFullUrl()` it may cause a breaking change. But since the package is new. No need to make it deprecated and create a new method to replace it.

Update README.md (Naming convention & some clarification)

Add LICENCE.md and make the package under MIT license.

### CODE REVIEW

**Comment by ayman-elmalah** [comment]
Could we update the license as the same page, 
https://opensource.org/licenses/MIT
without spatie license, we can change email to be aymanelmalah77@gmail.com

**Comment by ousid** [comment]
OH! Sorry for this mate.

I'll update this right away.

**Review by ousid — COMMENTED** [review]
Update email.

**Comment by ayman-elmalah** [comment]
Thanks for your contributing, merged done

**Pull request merged**
